### ISSUE TITLE
Update menu bar icon for Macs with a retina display

### ISSUE THREAD

**Issue by nograsswillgrow** [DanielStormApps/Fanny#1]
It appears that the current menu bar icon for Fanny is rather pixelated, especially when compared to a few other apps I use. If possible, it'd be great to see a high resolution icon in a future version if Fanny. I've attached a screenshot to show the comparison of Fanny to some other apps.

<img width="96" alt="screen shot 2016-02-22 at 12 10 19 pm" src="https://cloud.githubusercontent.com/assets/8907530/13226024/7fc09ec6-d95d-11e5-92c0-7008488d3994.png">

Thanks!

**Comment by DanielStormApps** [comment]
Updated. Thank you for pointing this out.

**Comment by fnc1996** [comment]
It appears that Fanny app doesn't work on Mac right now. I've attached a screenshot to show the bug 
<img width="171" alt="captura de ecra 2016-05-01 as 13 48 08" src="https://cloud.githubusercontent.com/assets/17252104/14941858/f11f210c-0fa2-11e6-8574-bdd9e53305ee.png">
