### ISSUE TITLE
Compatibility with older versions of macOS 

### ISSUE THREAD

**Issue by GeRoHi** [DanielStormApps/Fanny#11]
Hello, 
I tried to install Fanny on my mid-2010 macbook pro, v 10.11.6.
Figure out it is 10.12 locked since 1 month, can I find older version of your app to work on my machine ? 
Thanks !

**Comment by DanielStormApps** [comment]
You can download version 1.0.1 here: http://fannywidget.com/FannyWidget_v101.zip 👍
There are some minor issues with 1.0.1 though.
