### ISSUE TITLE
Our Data on com.DanielStorm.Fanny.FannyWidget 11.51.06 Container

### ISSUE THREAD

**Issue by djimnz** [DanielStormApps/Fanny#15]
Can you explain to us this Data directory with some alias targeted to our datas (pictures, iChats, Calendar, Documents, Desktop, etc... etc...) ? What are you doing ?

**Comment by DanielStormApps** [comment]
@djimnz I'm not sure what data directory you're referring to? Can you provide me with a directory path please.
