### ISSUE TITLE
Support Fahrenheit

### ISSUE THREAD

**Issue by dmyers** [DanielStormApps/Fanny#16]
Would this be possible as an option?

**Comment by shibatan** [comment]
Seconded. It would be nice to be able to toggle this.

**Comment by aharvard** [comment]
Yes, please!

**Comment by StevenKSanford** [comment]
Please!

**Comment by DanielStormApps** [comment]
Resolved in https://github.com/DanielStormApps/Fanny/commit/cec8011c7d7f9460afbb530b689594232208bad8 👍
