### ISSUE TITLE
Allow hiding of menu bar icon

### ISSUE THREAD

**Issue by sheepymeh** [DanielStormApps/Fanny#17]
Please allow Fanny's menu bar icon to be hidden, since the information can be accessed from the notification centre anyways, making the menu bar icon redundant.

**Comment by DanielStormApps** [comment]
The menu bar app is needed as its the widget extension's parent application.

**Comment by sadransh** [comment]
Is there any way to hide it?

**Comment by DanielStormApps** [comment]
@sadransh no, https://github.com/DanielStormApps/Fanny/issues/17#issuecomment-533852048
