### ISSUE TITLE
offer a build for older versions of macOS

### ISSUE THREAD

**Issue by ec1oud** [DanielStormApps/Fanny#19]
One of my machines has 10.11 so I had to build it myself.  It was no problem to set the Deployment Target in Xcode to 10.8 and do the build, but I haven't tried it yet on another machine which runs 10.9.  It works fine on the 10.11 machine.  So I think the binary on your web site should be compatible with as old a version of macOS as will work.

When I set it to 10.6 I see there is missing API, so it's impossible.  10.7: fewer errors - I think that might be possible.  I do have a machine running 10.7 that I could test it on.

There's also a warning:

Main.storyboard: warning: Unsupported Configuration: Automatic preferred width mode for static wrapping text before OS X 10.11, use Explicit or First Runtime Layout Width

Maybe that's OK, or maybe you need to have two versions, one for 10.11 and up, one for older versions.

Nice utility, anyway.  Thanks for writing it.

**Comment by ec1oud** [comment]
I just tried building on 10.7 with its old Xcode: I can't build the widget because of missing APIs, so I removed that.  (There's no notification sidebar anyway.)  Can't build the rest of it because you're using newer Objective C syntax than what the compiler supports.  Oh well.

At least 10.8 and up might be possible.

**Comment by DanielStormApps** [comment]
Supporting older versions of macOS is not a goal for this project.
