### ISSUE TITLE
application does not show data on late '08 Macbook

### ISSUE THREAD

**Issue by ih16** [DanielStormApps/Fanny#2]
The application does not show information about CPU temperature or fan speeds on a Late '08 Macbook 
(Macbook 5.1 A1278)

At startup it shows the following:
![schermafbeelding 2016-03-17 om 08 16 27](https://cloud.githubusercontent.com/assets/11390889/13839140/31749aaa-ec19-11e5-96bd-1a3369c2cc17.png)
which after a few seconds changes into 
![schermafbeelding 2016-03-17 om 08 20 32](https://cloud.githubusercontent.com/assets/11390889/13839148/3ca2594e-ec19-11e5-99d5-6e6236b5573b.png)

**Comment by airfoxa380** [comment]
Didn't work on an MacBook Retina late 2013.

**Comment by DanielStormApps** [comment]
I believe this is an issue with the System Management Controller(SMC) on Mac Book Pros returning incorrect values. I've been working on a fix with limited success. If anyone has any suggestions feel free to contribute. Resetting the SMC may help: [Reset the System Management Controller (SMC) on your Mac](https://support.apple.com/en-us/HT201295).

**Comment by ih16** [comment]
unfortunately I've tried that without success.. Both on the '08 and the '15 MacBooks..

**Comment by markimarc** [comment]
Same on my Macbook Air 2015

**Comment by Bonsailinse** [comment]
Yep, same on the '15 Retina. Are any fixes planned or do I have to look for an alternative?

**Comment by DanielStormApps** [comment]
fixed
