### ISSUE TITLE
macOS High Sierra missing notifier, grey data display

### ISSUE THREAD

**Issue by n7ihq** [DanielStormApps/Fanny#20]
I installed Fanny in macOS High Sierra on a 2016 MacBook Pro. The data appears as grey in the toolbar display. The Fanny app is not listed in Notifications. Any suggestions to fix this?

Thanks,

Jim

**Comment by jsibio** [comment]
Hi, same problem here, using MacOS High Sierra version 10.13.2

**Comment by jsibio** [comment]
ok, looks like you need to activate the Notification for Fanny from the Extension Menu (system preferences). Worked for me but data are still in grey from the toolbar.

**Comment by DanielStormApps** [comment]
Resolved in https://github.com/DanielStormApps/Fanny/commit/cec8011c7d7f9460afbb530b689594232208bad8 👍
