### ISSUE TITLE
Legacy Support? (10.9 and above)

### ISSUE THREAD

**Issue by christianjameswiles** [DanielStormApps/Fanny#22]
Hi! I have the Fanny app running on my main iMac, but I cannot for the life of me work out how to get this running on my Mid-2009 iMac, my secondary machine. I have tried build after build to no avail. I believe that this app would reach such a massive audience if it were supported on legacy OS X. Thanks!

**Comment by DanielStormApps** [comment]
Supporting older versions of macOS is not a goal of this project.

It may run though. Pull the project lower the deployment target in Xcode.
