### ISSUE TITLE
Fan Speed not showing after macbook resumes from sleep

### ISSUE THREAD

**Issue by moecantplay** [DanielStormApps/Fanny#23]
![screen-shot-2018-05-31-at-18 34 49](https://user-images.githubusercontent.com/28852435/40780197-c0845f24-6501-11e8-899f-a3d20208ef1f.jpg)

**Comment by DanielStormApps** [comment]
Resolved in https://github.com/DanielStormApps/Fanny/commit/cec8011c7d7f9460afbb530b689594232208bad8 👍
