### ISSUE TITLE
Please update app for MacBook Pro 2018

### ISSUE THREAD

**Issue by kayvanaarssen** [DanielStormApps/Fanny#25]
Hi,

Can you update the app for the new MacBook Pro 2018.
Fanspeed is now displaying -2323492 something.

Thanks.

<img width="321" alt="schermafbeelding 2018-07-24 om 07 39 08" src="https://user-images.githubusercontent.com/672841/43118950-b0bf6268-8f14-11e8-9c42-fc01caf6ab10.png">

**Comment by DanielStormApps** [comment]
Resolved in https://github.com/DanielStormApps/Fanny/commit/cec8011c7d7f9460afbb530b689594232208bad8 👍
