### ISSUE TITLE
FannyWidget: Dark Mode Support for Mojave

### ISSUE THREAD

**Issue by agaphetos** [DanielStormApps/Fanny#27]

**Comment by agaphetos** [comment]
Latest build shows grey colors for widget on notification center.

<img width="587" alt="screen shot 2018-10-02 at 6 39 13 pm" src="https://user-images.githubusercontent.com/7719506/46344069-841f1100-c672-11e8-9e44-e4336fe03f46.png">

**Comment by DanielStormApps** [comment]
Resolved in https://github.com/DanielStormApps/Fanny/commit/cec8011c7d7f9460afbb530b689594232208bad8 👍
