### ISSUE TITLE
Mac Mini 2018

### ISSUE THREAD

**Issue by slowrunner** [DanielStormApps/Fanny#29]

**Comment by litium** [comment]
![image](https://user-images.githubusercontent.com/1481171/50050607-1b0c4d00-013b-11e9-93f2-a84572551714.png)
mac mini 2018 reports invalid fan speed info

**Comment by slowrunner** [comment]
> fanny: mac mini 2018 reports invalid fan speed info

btw: Macs Fan Control 1.4.12 works well for me
