### ISSUE TITLE
Oversized menu bar icon.

### ISSUE THREAD

**Issue by nograsswillgrow** [DanielStormApps/Fanny#3]
This is a very minor request, but it does seem that the menu bar icon is a bit taller than most of the other icons shown on my Mac. Is it possible to shrink the icon down a bit to fit in with the rest of the apps? I've provided a screenshot that shows this. Thanks!

<img width="161" alt="screen shot 2016-03-19 at 10 15 55 am" src="https://cloud.githubusercontent.com/assets/8907530/13899123/09b98f26-edbc-11e5-8e04-5a17f36ae43b.png">

**Comment by svegan** [comment]
It will be great if there would be opportunity to hide icon at all as well.

**Comment by fcccbf8f8f1** [comment]
@nograsswillgrow, [here's](https://www.dropbox.com/s/ye42x86f3fjgcbk/fanIcon.png?dl=0) a smaller version of the menu bar icon (76 px vs 88 px): 

Just go to /Applications/Fanny.app/Contents/Resources/ and replace the existing fanIcon.png with one you download.

**Comment by nograsswillgrow** [comment]
@fcccbf8f8f1, thanks for providing this!
