### ISSUE TITLE
Fanny v1.0.3 Does Not Work For Mac Mini 2018 OSX 10.14.1 Mohave

### ISSUE THREAD

**Issue by slowrunner** [DanielStormApps/Fanny#30]
Fanny v1.0.3 worked great on my old Mac Mini 2012, but does not work on my new 2018 Mac Mini (OSX 10.14.1 Mohave).

![screen shot 2018-11-20 at 2 34 03 pm](https://user-images.githubusercontent.com/8950202/48797901-69136980-ecd1-11e8-89e8-f835d0d41b69.png)

**Comment by litium** [comment]
Same here. Mac Mini 2018 Mojave 10.14.2

**Comment by sitesfaction** [comment]
Mac pro 15 inch 2018, same problem =(

**Comment by DanielStormApps** [comment]
Resolved in https://github.com/DanielStormApps/Fanny/commit/cec8011c7d7f9460afbb530b689594232208bad8 👍
