### ISSUE TITLE
I think theres something wrong

### ISSUE THREAD

**Issue by GabrielCereals** [DanielStormApps/Fanny#31]
(MacBook Air 2018)
<img width="329" alt="screen shot 2019-01-11 at 9 20 19 pm" src="https://user-images.githubusercontent.com/26613957/51068654-e9c25800-15e6-11e9-8cc9-793cbe586bac.png">

also, what does the radio-button do?

**Comment by camlloyd** [comment]
IIRC, the number of radio buttons indicates the number of fans (e.g. one for 13", two for 15").
Clicking each radio button displays the stats for the respective fan.
You can check this against the stats for each fan in the menu bar.

Perhaps it would be better to add a label to the radio button, or hide it altogether if there is only one

**Comment by ryanrocket** [comment]
Having the same issue here :(

**Comment by DanielStormApps** [comment]
Resolved in https://github.com/DanielStormApps/Fanny/commit/cec8011c7d7f9460afbb530b689594232208bad8 👍
