### ISSUE TITLE
2019 Macbook Pro Support

### ISSUE THREAD

**Issue by jacob-hebert-roostify** [DanielStormApps/Fanny#34]
Does not appear to work with the 2019 Macbook Pros. 

![image](https://user-images.githubusercontent.com/52979012/63055354-4f433380-beab-11e9-8bb5-a492d861c2d8.png)

**Comment by marclundgren** [comment]
https://github.com/DanielStormApps/Fanny/issues/31

**Comment by Reevak05** [comment]
Yep. Same problem.

**Comment by DanielStormApps** [comment]
Resolved in https://github.com/DanielStormApps/Fanny/commit/cec8011c7d7f9460afbb530b689594232208bad8 👍
