### ISSUE TITLE
FannyWidget not responding (macOS Sierra)

### ISSUE THREAD

**Issue by stefanhendriks** [DanielStormApps/Fanny#35]
Installed 2.0.

Appears in top bar, cannot click it (no response) - there is an icon though.

In notification bar:
<img width="336" alt="image" src="https://user-images.githubusercontent.com/1332066/65832020-fd6e3580-e2bf-11e9-8fb1-e1b90e486d17.png">

Is there an older version to test? ( i tried the download link in #11, but that gave a 404)

**Comment by stefanhendriks** [comment]
I have upgrade to Mojave and things work fine now. So it looks like a mac OS Sierra thing.

**Comment by Magneticdud** [comment]
I have exactly the same problem with macos 10.13.6

Can't update to latest versions because Apple decided my iMac is not good enough, even though it has faster CPU and has more RAM than a brand new Mac Mini 2019

**Comment by DanielStormApps** [comment]
@Magneticdud can you launch the Console (~/Applications/Utilities/Console.app) application, start Fanny, and post any Fanny related logs here please.

Xcode does not allow for a way to simulate running on older versions of macOS so debugging this issue is very tedious, have to partition, install, and boot older macOS versions. If you're able to capture some information for me to narrow down the issue that'd be greatly appreciated.

**Comment by Magneticdud** [comment]
I have this in console:

```
errore	17:06:47.922553 +0200	Fanny	Couldn't read values in CFPrefsPlistSource<0x6040000f8980> (Domain: fanny-shared-defaults, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
default	17:06:47.923377 +0200	Fanny	-[Fanny.FNYMenu setItemArray:]: unrecognized selector sent to instance 0x6000002636c0
default	17:06:47.923637 +0200	Fanny	-[Fanny.FNYMenu setItemArray:]: unrecognized selector sent to instance 0x6000002636c0
default	17:06:47.924303 +0200	Fanny	        OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(spec,phac handler=0x7fff41a32a98 isSys=YES) err=0/noErr
default	17:06:57.424760 +0200	Fanny	LSExceptions shared instance invalidated for timeout.
```

**Comment by DanielStormApps** [comment]
@Magneticdud perfect thank you! Looks to be an issue with setting the menu items on the menu. Narrows it down a lot. I’ll take a look 👍

**Comment by DanielStormApps** [comment]
@Magneticdud resolved with https://github.com/DanielStormApps/Fanny/commit/c0bc89f7a2eba91694e2c4f6c9e5edb5e209c8ee

New version, 2.0.1, available on https://www.fannywidget.com 

Closing issue. Reopen if problem persists.

**Comment by Magneticdud** [comment]
![immagine](https://user-images.githubusercontent.com/2940598/65897417-84e6a200-e3af-11e9-9644-ee3ad02ebae1.png)

works!

(my cpu too hot, time to blast the fans full speed with ssd fan control :) )

**Comment by stefanhendriks** [comment]
@DanielStormApps awesome! thanks
