### ISSUE TITLE
MacBook Air 2013 GPU is 0 degrees celsius

### ISSUE THREAD

**Issue by fedekrum** [DanielStormApps/Fanny#36]
Hi
Thanks for the app.
My MacBook Air 2013 is telling me that the GPU is 0 degrees celsius.
Temperature at home is 24 degrees and cpu is 53.
Looks like or there is no temperature sensor, or some other situation.
Thanks

**Comment by DanielStormApps** [comment]
Thank you for opening this issue.
Debating on how we should handle this. There's multiple sensors that could work or not per machine and not much info available on what works where. I may update SMC to fallback to another sensor if the current one fails, no guarantee that that will work either though. Or, I may hide the GPU output label if we're unable to get an actual temperature.
Will work on something and let you know. May need you to run the build on your machine to confirm implementation.
Thanks again!

**Comment by OscarBarrett** [comment]
Same here with a Late 2013 Macbook Pro (MacBookPro11,2) which has an integrated Intel Iris Pro.

Looking at [istats](https://github.com/Chris911/iStats/blob/dff9569c2952b6118dfc2ee6fab96fb06954906a/lib/iStats/smc.rb#L67), the sensor key for the PECI GPU sensor is `TCGC` and in [SMC](https://github.com/DanielStormApps/SMC/blob/13e0662403fe2a567aa326b4eb34324ecc531df4/smc/SMC/SMC%2BSensor.swift#L25) you're only checking `TG0P` which is for GPU 0.

**Comment by DanielStormApps** [comment]
Thank you for providing the code @OscarBarrett ! 👍 

Haven't had to time to get around to this just yet.

**Comment by CarlyRaeJepsenStan** [comment]
Hope you get to it soon Daniel!  My MacBook Pro Mid 2015 model also has the same issue where GPU appears as 32ºF

**Comment by dj-ellis** [comment]
Same issue on a 2019 MacBook Pro...

Happy to test when a solution is found.

Thanks

**Comment by atymic** [comment]
Pretty similar issue, temp from the power gadget is much higher.
It seems intel is taking the temp of the actual cores, whereas this is using a different sensor. The tempreture reported by fanny seems sus to me, as it's always an integer (ie. never 55.xx degrees, always 55.00).

<img width="608" alt="Screen Shot 2020-01-31 at 12 36 02 pm" src="https://user-images.githubusercontent.com/50683531/73505380-77592b80-4426-11ea-89b5-ea935ac5130a.png">

**Comment by atymic** [comment]
Here's all of the available sensors. I think a better representation of the CPU temp would be the average of the CPU cores, similar to power tool.

![image](https://user-images.githubusercontent.com/50683531/73505716-64932680-4427-11ea-8fbc-eb7e0c54f861.png)

**Comment by CarlyRaeJepsenStan** [comment]
@atymic just curious is that Macs Fan Control?

**Comment by atymic** [comment]
Yep @CarlyRaeJepsenStan

**Comment by CarlyRaeJepsenStan** [comment]
@atymic Cool!  
On a more related note my widget still displays GPU temp as 0C/32F.

**Comment by BogdanPatroi** [comment]
Same GPU issue here.

_MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
2,3 GHz Dual-Core Intel Core i5
8 GB 2133 MHz LPDDR3
Intel Iris Plus Graphics 640 1536 MB_

**Comment by DanielStormApps** [comment]
Resolved in v2.1.0 🚀
Download the latest version from https://www.fannywidget.com

If issue persists please open a new issue.

Thank you for the details on this issue everyone! 👍
