### ISSUE TITLE
wrong temperature display

### ISSUE THREAD

**Issue by geniusxburhan** [DanielStormApps/Fanny#37]
hello there. i am using two program to check cpu temperature. first intel power gadget, second fanny. but intel power gadget temperature is (always)4 degrees higher than fanny.

**Comment by DanielStormApps** [comment]
There's multiple sensors for monitoring temperatures. Fanny uses the proximity sensor. I'm not sure which sensor Intel Power Gadget uses. Is this software free? Can you provide a link to download?

**Comment by geniusxburhan** [comment]
> There's multiple sensors for monitoring temperatures. Fanny uses the proximity sensor. I'm not sure which sensor Intel Power Gadget uses. Is this software free? Can you provide a link to download?

sure! https://software.intel.com/en-us/articles/intel-power-gadget

**Comment by DanielStormApps** [comment]
Consolidating to https://github.com/DanielStormApps/Fanny/issues/36
