### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by Richard195666** [DanielStormApps/Fanny#38]
It does not work on new 16 inch MacBook Pro.

**Comment by DanielStormApps** [comment]
Can you be more specific as to what is not working exactly please.

**Comment by Richard195666** [comment]
It said 
Current Speed: 13115 RPM
Target Speed: 32
Mini Speed: 32
Max Speed: 32
These numbers make no sense.

**Comment by Richard195666** [comment]
By the way, the system is 10.15.1

**Comment by DanielStormApps** [comment]
Consolidating to https://github.com/DanielStormApps/Fanny/issues/36
