### ISSUE TITLE
32-bit Integer overflow on MacBook Pro 16" runs macOS 10.15.2

### ISSUE THREAD

**Issue by liuziangexit** [DanielStormApps/Fanny#39]
Hello Sir.
Your Fanny app is stunning, I'm using it for a year on my MacBook Pro 13" runs 10.14 Mojave.
Recently i updated to the new MBP 16" with 10.15, and I realize there is an overflow bug in Fanny so that I opened this issue.

![image](https://user-images.githubusercontent.com/15322450/71446135-0786bf80-275b-11ea-85a3-8b4412dba4c4.png)
![image](https://user-images.githubusercontent.com/15322450/71446138-0ce40a00-275b-11ea-943c-06cf830ff5ed.png)

**Comment by DanielStormApps** [comment]
Thank you for opening the issue. 
This issue is resolved in the latest version of Fanny. Please update https://www.fannywidget.com/
