### ISSUE TITLE
Wrong Values

### ISSUE THREAD

**Issue by airfoxa380** [DanielStormApps/Fanny#4]
Hey, 

I think the sensor values didn't male sense, also the temperatur seems to be,....to hot.

**Comment by airfoxa380** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="nNIw977"><a href="//imgur.com/nNIw977">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by collateraldamadge** [comment]
I have the same problem. All fan speeds are 0, and temperature is > 52000 degrees. 
Mac Book Pro with OS X 10.11.5.

Any solutions?

**Comment by airfoxa380** [comment]
Well,...no. It's not really a solution but don't use it? There are some other tools,...

**Comment by kusmierz** [comment]
@airfoxa380 what tools? could you give some examples? I've similar issue.

**Comment by airfoxa380** [comment]
well you could use iStat menu,…just google for it.

Mit freundlichen Grüßen,

Oliver Dorn


____________________
I support GPG on this e-mail: Oliverdorn1@gmx.de

or ask friendly for the pub key

**Comment by sniok** [comment]
![image](https://cloud.githubusercontent.com/assets/4517681/17035456/f8d3ab2a-4f8f-11e6-88f1-43665883697d.png)
Same problem. MacBook Pro, OS X 10.11

**Comment by 3mg4** [comment]
Same problem here, looks like to be a decimal mistake maybe...

**Comment by DanielStormApps** [comment]
I believe this is an issue with the System Management Controller(SMC) on Mac Book Pros returning incorrect values. I've been working on a fix with limited success. If anyone has any suggestions feel free to contribute. Resetting the SMC may help: [Reset the System Management Controller (SMC) on your Mac](https://support.apple.com/en-us/HT201295).

**Comment by Git-Jiro** [comment]
@DanielStormApps I have the same issue (OS X 10.11.6 MacBook Pro Mid 2012).
I already tried resetting the SMC. Unfortunately it did not help.

**Comment by isyara** [comment]
@DanielStormApps I have the same issue with OS X 10.11.6 MacBook Pro 2015

<img width="167" alt="fanny" src="https://cloud.githubusercontent.com/assets/2648791/17929111/a652f520-69fe-11e6-966a-87c36f06ef12.png">

**Comment by DrBones** [comment]
@DanielStormApps On a MBPr from 2013 I encounter the same issue. 
Apart from a decimal point issue the temperature readout seems to be fine. At least compared to the iStats ruby gem which uses the mystical smc.c and smc.h files. The fan rpm values do not show any fan activity even if the fans are very audible in contrast to the iStats gem.

Such a shame since it looks quite nice in the Notification Center :)

**Comment by ajanini** [comment]
+1

**Comment by LordPum** [comment]
![schermata 2016-09-01 alle 1 49 44 pm](https://cloud.githubusercontent.com/assets/21661242/18166394/3875e8de-704b-11e6-9c34-151d6bf69810.png)
Mac Mini Mid 2011 running MacOS 10.11.6

**Comment by fonorobert** [comment]
![screen shot 2016-09-01 at 15 09 16](https://cloud.githubusercontent.com/assets/6963710/18168461/14ea5fa2-7056-11e6-9f74-e2662e536207.png)
MacBook Pro 13" retina late 2015

**Comment by SandroSimes** [comment]
<img width="162" alt="screen shot 2016-09-13 at 05 42 08" src="https://cloud.githubusercontent.com/assets/14862315/18461779/dcfa13ee-7974-11e6-98b0-a275e203dcc4.png">

MacBook Pro 13" retina late 2015

**Comment by smbss** [comment]
<img width="162" alt="screen shot 2016-09-13 at 05 42 08" src="https://cloud.githubusercontent.com/assets/14862315/18461854/82e2f5fa-7975-11e6-9081-420c0b56986d.png">
MacBook Pro 13" retina late 2015

**Comment by DanielStormApps** [comment]
Fixed

**Comment by Git-Jiro** [comment]
Works great in Sierra now! Thank you so much!
