### ISSUE TITLE
Wrong temperature shown on 2.2.0 and 2.1.0

### ISSUE THREAD

**Issue by nguyenhungtogiang** [DanielStormApps/Fanny#45]
There are 3 different temperatures being shown for the CPU.
It should be noted before updating to version 2.2.0 and 2.1.0 CleanMyMac X, Temp Moniter and Fanny showed the same temperature for the CPU. After updating Fanny shows different, higher temperatures and the other application still has the same temperature. 
<img width="482" alt="Ảnh chụp Màn hình 2020-04-11 lúc 15 31 04" src="https://user-images.githubusercontent.com/43960444/79039272-583aff00-7c0a-11ea-80ab-133ee7deca1b.png">

**Comment by DanielStormApps** [comment]
The temperature is now an average of sensor readings instead of just the proximity sensor
https://github.com/DanielStormApps/Fanny/issues/41

**Comment by nguyenhungtogiang** [comment]
So which one is more accurate?

**Comment by DanielStormApps** [comment]
I can’t speak to the accuracy of the other apps. The temperature is more about having a reference point than absolute accuracy. 

If you’d like to be able to select which sensor is used, or which sensors are computed in the average, please submit a feature request. 👍

**Comment by nguyenhungtogiang** [comment]
Okay. Thank’s you so much

**Comment by DanielStormApps** [comment]
v2.3.0 now allows you to select which sensor is used for the CPU/GPU readings.

Select "Proximity" for both the CPU and GPU under preferences to get the same behavior as version v2.1.0 👍
