### ISSUE TITLE
Document installation via homebrew

### ISSUE THREAD

**Issue by kishaningithub** [DanielStormApps/Fanny#50]
I see that a [hombrew-cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/fanny.rb) is available for this package and thanks to that `brew cask install fanny` just works. This is also very good for upgrades as i just do `brew cask upgrade` and every gui app that i have just upgrades itself magically.

Not sure where the source code of your site is hosted. if you can point me in that direction i can raise a PR adding this installation method to the documentation

**Comment by SpaceKatt** [comment]
Verified this works

**Comment by DanielStormApps** [comment]
https://www.fannywidget.com is not open sourced, for now at least.

**Comment by AlbertVilaCalvo** [comment]
> https://www.fannywidget.com is not open sourced, for now at least.

@DanielStormApps would be nice to add the command `brew cask install fanny` though. I had to search for 'brew' on the GitHub search box.
