### ISSUE TITLE
Request to Download Older Versions of the App

### ISSUE THREAD

**Issue by PhluXx1** [DanielStormApps/Fanny#62]
I'm experiencing issues with the latest version (2.3.0) on my Macbook Pro 2012, it's displaying incorrect temperature readings and I want to revert to an older version which worked for me before.

Could you please provide a download link for v2.0.1 of the application? Access to all of the older versions would be helpful and appreciated too.

**Comment by RutgerMensen** [comment]
@PhluXx1: https://github.com/DanielStormApps/Fanny/releases/tag/2.0.1

Any other releases can also be found there: https://github.com/DanielStormApps/Fanny/releases
