### ISSUE TITLE
Feature Request: change color if temperature is higher than x

### ISSUE THREAD

**Issue by helmut72** [DanielStormApps/Fanny#67]
Subject says it all. Thank you.

**Comment by roberthchan** [comment]
So depends to mac´s model set predetermined temp, color indicator

**Comment by helmut72** [comment]
That's why I wrote x, a configurable variable ;-) Also people want to set individual numbers for some reasons.

**Comment by asheenlevrai** [comment]
+1

**Comment by helmut72** [comment]
Doesn't use it anymore.
