### ISSUE TITLE
Cannot be seen in Notification Center

### ISSUE THREAD

**Issue by jpyces** [DanielStormApps/Fanny#77]
Cannot see the widget of this app in notification centre in MacOS 11.3 (Big SUR)

**Comment by ck196** [comment]
I got the same problem in bigSur 11.4 (Mac Air M1)

**Comment by jurejuvuify** [comment]
Likewise. :/

**Comment by jpyces** [comment]
same

**Comment by nbcarey** [comment]
Same here. MacOS Catalina (10.15.7).

**Comment by Eselfar** [comment]
Same here. It doesn't appear on the widgets list (Big Sur 11.4, MBP 2018, Fanny 2.3.0)

**Comment by gpparker** [comment]
Ditto, but at first I _could_ see it in the menu bar. Then I changed preferences to show GPU temp and lost all visual, but the process is still running. Killing and restarting does not help. (Big Sur 11.5.2, iMac w/M1)

**Comment by mirobertod** [comment]
Same here.

macOS Big Sur 11.5 - MacBook Pro 16-inch, 2019

**Comment by alexlana777** [comment]
Same here

**Comment by sparsh-kamat** [comment]
Yup same on M1 Macbook air running monterey

**Comment by jpyces** [comment]
you just have to run it
install it and everytime you wanna use it, you have to manually open it.

I did install it on Big Sur and not Monterey on a 2017 MacBook Air 

but it shouldn't matter, it works, just not as advertised anymore

it shows up in the global menu bar
