### ISSUE TITLE
Prevent continuous logging to system.log

### ISSUE THREAD

**Issue by fcccbf8f8f1** [DanielStormApps/Fanny#8]
Is there any way to prevent Fanny from logging all fan info to system.log every 3 seconds? This seems a little excessive.

**Comment by DanielStormApps** [comment]
You can remove the `NSLog` statements or add: `// Disable NSLog
#define NSLog(...)` to the top of every file. I'll try to get a new version out this week that implements this.

**Comment by fcccbf8f8f1** [comment]
Thanks for the update!
